apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-letsencrypt-issuer
  labels:
    app.kubernetes.io/app: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mirnes.halilovic@serapion.net
    privateKeySecretRef:
      name: {{ .Values.global.tls.secretName }}
    solvers:
      - http01:
          ingress:
            class: nginx 
