{{- range $serviceName, $service := .Values.services }}
{{- if $service.configMap }}
{{- if $service.configMap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $serviceName }}-config
  labels:
    app.kubernetes.io/app: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/component: {{ $serviceName }}
data:
  {{- range $key, $value := $service.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
