{{- range $serviceName, $service := .Values.services }}
{{- $root := $ }}
{{- $fullname := include "common.fullname" (dict "Release" $root.Release "Chart" $root.Chart "serviceName" $serviceName) }}
{{- $labels := include "common.labels" (dict "Release" $root.Release "Chart" $root.Chart "serviceName" $serviceName) }}

{{- with $service.autoscaling }}
{{- if .enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullname }}
  labels:
{{ $labels | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $fullname }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
{{- end }}
