{{- if .Values.global.image.registryCredentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.image.registryCredentials.name }}
  labels:
    app.kubernetes.io/app: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.global.image.registryCredentials.registry .Values.global.image.registryCredentials.username .Values.global.image.registryCredentials.password .Values.global.image.registryCredentials.email (printf "%s:%s" .Values.global.image.registryCredentials.username .Values.global.image.registryCredentials.password | b64enc) | b64enc }}
{{- end }}
