{{- $novaCoreHost := (index (index (index $.Values.services "nova-core") "ingress") "hosts" 0).host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app.kubernetes.io/app: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location / {
        if ($host = "{{ $novaCoreHost }}") {
          proxy_set_header Connection '';
          proxy_http_version 1.1;
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
        }
      }
spec:
  tls:
    - secretName: {{ .Values.global.tls.secretName }}
      hosts:
      {{- range $serviceName, $service := .Values.services }}
        {{- if $service.ingress.enabled }}
        {{- range $host := $service.ingress.hosts }}
        - {{ $host.host }}
        {{- end }}
        {{- end }}
      {{- end }}
  rules:
  {{- range $serviceName, $service := .Values.services }}
    {{- if $service.ingress.enabled }}
    - host: {{ (index $service.ingress.hosts 0).host }}
      http:
        paths:
        {{- range (index $service.ingress.hosts 0).paths }}
        - path: {{ .path }}
          pathType: {{ .pathType }}
          backend:
            service:
              name: {{ $serviceName }}
              port:
                number: {{ (index $service "service").port | default $.Values.global.port }}
        {{- end }}
    {{- end }}
  {{- end }}

