{{- range $serviceName, $service := .Values.services }}
{{- $root := $ }}
{{- $fullname := include "common.fullname" (dict "Release" $root.Release "Chart" $root.Chart "serviceName" $serviceName) }}
{{- $labels := include "common.labels" (dict "Release" $root.Release "Chart" $root.Chart "serviceName" $serviceName) }}

{{- with $service.ingress }}
{{- if .enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
{{ $labels | nindent 4 }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
spec:
  rules:
    {{- range .hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullname }}
                port:
                  number: {{ (index $service "service").port | default $.Values.global.port }}
          {{- end }}
    {{- end }}
  tls:
    {{- toYaml .tls | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
