{{- range $serviceName, $service := .Values.services }}
{{- $root := $ }}
{{- $fullname := include "common.fullname" (dict "Release" $root.Release "Chart" $root.Chart "serviceName" $serviceName) }}
{{- $labels := include "common.labels" (dict "Release" $root.Release "Chart" $root.Chart "serviceName" $serviceName) }}

{{- with $service.serviceAccount }}
{{- if .create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name | default (printf "%s-sa" $fullname) }}
  labels:
{{ $labels | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
